var dbposts = {
    posts: [
        {
        "titulo" : "paiN Gaming anuncia campanha de auxílio e conscientização no mês do orgulho LGBTQ+",
        "data" : "14/06/2019",
        "imagem" : "img/pain-gaming-anuncia-campanha-lgbt.jpg",
        "texto" : "O mês de junho é considerado o mês do orgulho LGBTQ+. No início do mês, diversas organizações de eSports anunciaram apoio à causa mas a paiN Gaming fez mais do que aderir. A equipe anunciou nesta semana uma campana com o objetivo de unir a comunidade e os torcedores para angariar doações para a Casa 1 (centro de acolhimento de LGBTs expulsos de casa) e atuar na conscientização da comunidade.A Casa 1 é uma organização localizada na região central da cidade de São Paulo e financiada coletivamente pela sociedade. Atuando em três frentes principais: república de acolhida para pessoas LGBT expulsas de casa por suas orientações afetivas sexuais e identidades de gênero; um centro cultural, o Galpão Casa 1, que conta com atividades culturais e educativas, que tem como foco promover a diversidade cultural, fomentar a produção de conhecimento e cultura livre e constituir uma programação gratuita, inclusiva e de qualidade para seus diversos públicos; a entidade quase encerrou as suas atividades por falta de recursos financeiros. A notícia se espalhou e a comunidade se engajou para formar um financiamento coletivo online.A paiN resolveu então participar do movimento e por meio de sua força no cenário alavancar o apoio vindo de seus torcedores e apoiadores. Uma de suas principais estrelas, Gustavo “Minerva” Queiroz comentou sobre a importância de ações como essa para o cenário.- A campanha da paiN é muito importante e é mais um dos motivos que me deixam muito feliz por trabalhar aqui. Nosso cenário ainda é muito problemático e me orgulha ver meu time encabeçando uma campanha como essa, com objetivo de tornar a comunidade melhor. Isso tudo além de ajudar a Casa 1, um lugar que ajuda muitas pessoas e cumpre um papel muito legal e muito importante aqui em São Paulo - finalizou. ",
    },{
        "titulo" : "Watch Dogs Legion terá milhares de personagens e morte definitiva",
        "data" : "13/06/2019",
        "imagem" : "img/whatsapp-image-2019-06-11-at-17.32.49.jpeg",
        "texto" : "Watch Dogs Legion tem o objetivo de levar a já popular franquia a um novo nível. O jogo para PS4, Xbox One e PC, apresentado pela Ubisoft na E3 2019, mantém a premissa original de hackers em um mundo aberto. Mas, dessa vez, permite que se jogue com todos as pessoas que você cruzar pelo caminho - ou seja, não existem figurantes, qualquer um dos milhares de personagens existentes podem ser jogáveis.A história do game, apesar de não muito original, encaixa muito bem na proposta. Em uma Londres dominada pelo autoritarismo, corrupção e máfia, a população vive de forma caótica e sem esperança. Porém, uma organização de resistência chamada DedSec se usa da tecnologia para tentar livrar o país dessas ameaças políticas e sociais. A grande sacada na trama é o fato de não existir um personagem central. Você pode ser qualquer cidadão, e formar o grupo da resistência com todos os personagens com quem você cruzar no mapa.No teste, por exemplo, começamos jogando com uma senhora de idade, chamada Sophia. Acessando o perfil da personagem, é possível ver tudo: nome, idade, profissão, salário, estado civil etc. Com ela, entramos em um bar e começamos a hackear cada um das dezenas de pessoas que estavam ali, checando a vida de cada uma. Depois disso, foram escolhidas as pessoas mais interessantes para se unir à resistência. Para recrutar alguém, é preciso cumprir pequenas missões, até que ela esteja disponível para entrar no grupo e, assim, se tornar jogável.O jogo tem uma complexidade muito grande, já que é possível acompanhar a vida de todos ao redor, e cada um dos personagens tem traços de personalidade bem marcantes. Além disso, todas as mortes do jogo são permanentes - ou seja, se uma pessoa que você está controlando morrer na missão, é para sempre, mesmo que você crie uma afinidade enorme com ela. E não só isso: caso o personagem seja pego pela polícia e acabe na cadeia, por exemplo, é preciso esperar todo seu tempo de penitência para voltar a ser jogável. A não ser que você arrisque invadir para tirá-lo de lá... Os gráficos de Watch Dogs Legion também são um destaque. Principalmente em relação à cidade de Londres, que foi recriada com muita perfeição. Vale a pena parar e dar uma olhada nos detalhes ao redor e até dentro dos prédios - os bares ingleses, por exemplo, são muito ricos em detalhes e têm uma ambientação perfeita. Vale lembrar que, nos PC, o game suportará DirectX Raytracing em máquinas equipadas com NVIDIA GeForce RTX, levando um realismo ainda maior para os jogadores nesta plataforma.Já em questão de jogabilidade, o novo Watch Dogs não traz nada que os antigos games da série já não tenham. Os ataques hackers, os tiros, os roubos de veículos. Tudo é bem parecido com o que já estamos acostumados, inclusive em outros títulos de mundo aberto. Ou seja: a principal aposta do Legion é mesmo na inovação de se jogar com centenas de personalidades diferentes. "
    },{
        "titulo" : "E3 2019: DLC De KINGDOM HEARTS 3 tem detalhes revelados",
        "data" : "12/06/2019",
        "imagem" : "img/Kingdom-Hearts-III-tem-novo-trailer-anunciado.jpg",
        "texto" : "Durante um teaser trailer exibido com exclusividade na Kingdom Hearts Orchestra: World of Tres, em Los Angeles, a Square Enix mostrou imagens do DLC, que ainda está em desenvolvimento. O estúdio confirmou que os jogadores poderão controlar Roxas, Riku e Aqua, enquanto os gameplays exibidos parecem colocá-los em lutas contra chefões durante a batalha que acontece no final do jogo base no Cemitério de Keyblade.Em outra cena, Sora muda para o que parece ser a forma da Oathkeeper Keyblade, usando uma roupa branca e a arma temática. A luta acontece em Scala ad Caelum, mundo que também já apareceu no game base.Ainda, o trailer inclui detalhes intrigantes de história. O primeiro coloca o jovem Master Xehanort em conversa com quem parecer ser o Mestre dos Mestres. Xehanort indica que percebeu que ele é mais importante do que pensava.Em outra cena, o diálogo de Luxord e Xigbar parece estar ligado ao epílogo de Kingdom Hearts 3, com ambos questionando suas identidades. O DLC ainda não tem uma data de lançamento, mas o diretor Tetsuya Nomura promete que mais novidades serão reveladas em breve"
    },{
        "titulo" : "Pokémon Sword e Shield não terá suporte a todos os Pokémon existentes",
        "data" : "11/06/2019",
        "imagem" : "img/pokemon1.jpg",
        "texto" : "Junichi Masuda, um dos diretores da Game Freak, afirmou em stream da E3 2019 que nem todos os Pokémon serão suportados em Pokémon Sword e Shield.Infelizmente, os desenvolvedores limitaram os monstrinhos do game apenas àqueles que aparecem na região de Galar, onde o jogo se passa, sejam eles da atual geração ou das passadas. Isso significa que mesmo as transferências possibilitadas pelo serviço Pokémon Home serão limitadas aos monstrinhos da Pokédex local.Agora que nós estamos bem acima das 800 espécies de Pokémon, na Game Freak nós passamos bastante tempo pensando em qual seria o melhor passo a ser dado - realmente preservar a qualidade dos diferentes Pokémon, ao mesmo tempo que levamos em conta o balanceamento das batalhas por ter tantos Pokémon diferentes disponíveis, explica Masuda. Com um tempo de desenvolvimento limitado, Masuda afirma que os desenvolvedores prefiram que os fãs não tivessem que esperar tanto tempo por um novo jogo, e afirma que eles foram muito cuidadosos ao escolher a melhor seleção de Pokémon para a ambientação da aventura.Um detalhe interessante, também confirmado durante a E3 2019, foi o de que todos os shinies capturados em Pokémon Let's Go serão aceitos na nova geração - desde que eles façam parte da Pokédex de Galar."
    },{
        "titulo" : "paiN Gaming anuncia campanha de auxílio e conscientização no mês do orgulho LGBTQ+",
        "data" : "10/06/2019",
        "imagem" : "img/1E7BP97U0XAH1533227441212.jpg",
        "texto" : "A Blizzard está perdendo um dos grandes nomes do seu setor de eSports. Nate Nanzer, conhecido por ser o principal responsável pela Overwatch League, vai deixar a gigante para seguir para a Epic Games.A nova função de Nanzer será exatamente a de explorar as potencialidades de Fornite, o game de maior sucesso da atualidade no setor de eSports. O título, apesar de todo barulho, ainda derrapa em encontrar um bom modelo que encaixe no estilo Battle Royale.A notícia foi trazida pela ESPN e depois confirmada pelo próprio desenvolvedor no Twitter. “Hey, família Overwatch League. Gostaria de compartilhar que, em breve, eu sairei da Blizzard para uma nova oportunidade. Esta tem sido a decisão mais difícil da minha vida, pois significa que eu não poderei mais trabalhar com o melhor time, jogadores, equipes, donos, parceiros e fãs do eSport”, escreveu em sua rede social.Nanzer entrou para a Blizzard em 2014, quando trabalhou no modelo da Overwatch League, ajudando a alçar o game de tiro, na época recém-lançado, ao topo de uma das competições mundiais mais importantes.A Epic está apostando forte em seu principal jogo. Atualmente, a desenvolvedora anunciou um aporte de US$ 100 milhões para a Copa do Mundo de Fortnite. A final, que deve acontecer agora em julho, conta com premiação de US$ 30 milhões. O investimento em Nanzer, um grande figurão do mercado, também pode mostrar que a Epic está disposta a investir no setor.Do lado da Blizzard, o posto será preenchido por Pete Vlastelica. Ele foi vice-presidente da Fox Sports nos Estados Unidos e já participa de decisões dentro do cenário de eSpots da companhia.“Estou confiante de que a liga está em boas mão. Mal posso esperar para ver para onde o time vai levar a Overwatch League em 2020 - e além. Estarei torcendo daqui ao lado de vocês, a cada passo dado”, finalizou Nazer em comunicado."
    }
]
}